export const INCREMENT = "INCREMENT";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FILTER_BY_TITLE = "FILTER_BY_TITLE";
export const SET_DATE_RANGE_FILTER = "SET_DATE_RANGE_FILTER";
export const SET_TITLE_FILTER = "SET_TITLE_FILTER";
export const FILTER_BY_DATE_RANGE = "FILTER_BY_DATE_RANGE";
export const RESET_FILTERS = "RESET_FILTERS";
